POST https://node-do-zero-z3nf.onrender.com/videos
Content-type: application/json

{
    "title": "Aula 03 - PHP",
    "description": "Este é o video 03",
    "duration": 200
}

###

GET https://node-do-zero-z3nf.onrender.com/videos
###

GET https://node-do-zero-z3nf.onrender.com/videos?search=php

###

PUT https://node-do-zero-z3nf.onrender.com/videos/88ed32e4-4ead-40e4-a6c5-0ac88ca0d268
Content-type: application/json

{
    "title": "Aula 02 - PHP",
    "description": "Este é o segundo video",
    "duration": 200
}

###

DELETE https://node-do-zero-z3nf.onrender.com/videos/33504f9f-12c8-4ada-9a99-4bba10659c66
